module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  USER_DECLINED: 'USER_DECLINED',
  USER_ACCEPTED: 'USER_ACCEPTED',
  MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT',
  END_SESSION: 'END_SESSION'
};
